language: python
 - "python"

python:
  - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:
  - "source .env"
  - "pytest --with-coverage --cover-package=test --cover-package=app
 && coverage report"

after_success:
  - "coveralls"

after_success:
  "coveralls"


